### PR TITLE
Add TravisCI setup

### PR DESCRIPTION
**Pull request by hauleth**

### CODE REVIEW

**Comment by hauleth** [comment]
Fixed.

**Comment by briansmith** [comment]
Great. Please squash the changes and then I'll merge the PR.

**Comment by briansmith** [comment]
I updated the Travis CI afterwards. Please see:
2f17dbfc5e3a047165d401647abc201e3acea2f3
42dabb3c9f31613795011af47b8bfd325b83dcaf
89d591e6448310fcd2885c028ae8b745e52eb8bc
d6459f92fa416a1bfee6bc93d572aec07df72107

The biggest change is from `cargo bench` to `cargo test --release`.

**Comment by briansmith** [comment]
I activated Travis CI for my copy of the repo, and everything is green: https://travis-ci.org/briansmith/crypto-bench/builds/87569797

Also, I am going to file some issues about expanding the test coverage.

**Comment by hauleth** [comment]
:+1:

**Pull request merged**
